# Generated by Django 2.2.3 on 2019-07-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionrule',
            name='usage_type',
            field=models.CharField(choices=[('once_per_account', 'Can only be used once per account'), ('first_recharge', 'Can only be used during first recharge.'), ('multi_use', 'Can be used multiple times by multiple account')], default='once_per_account', max_length=128, verbose_name='Usage Type (Account level)'),
        ),
    ]
